config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'base#index'

    resources :xfiles, only: [:new, :create, :destroy]
    resources :users
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  devise_for :users

  root 'xfiles#index'

  resources :xfiles, only: [:index, :show, :edit, :update] do
    resources :notes do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :notes, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :assets, only: [:show, :new], path: :files
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def remove
		@note = Note.find(params[:note_id])
		@tag = Tag.find(params[:id])

		authorize @note, :tag?

		@note.tags.destroy(@tag)
		head :ok
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<!--<%= f.simple_fields_for :tags do | ff | %>-->
	<%= f.input :tag_names, label:"Tags" %>
<!--<% end %>-->

app/views/tags/_tag.html.erb
<div class="tag">
	<% if policy(note).tag? %>
		<%= link_to "<span></span>".html_safe, remove_note_tag_path(note, tag), method: :delete, remote: true, class: "remove", title: "remove" %>
	<% end %>
	<%= link_to tag.name, search_xfile_notes_path(@note.xfile, search: "tag:#{tag.name}") %>
</div>