config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root 'base#index'

    resources :xfiles, only: [:new, :create, :destroy]
    resources :users
    resources :states, only: [:index, :new, :create] do
      member do
        get :make_default
      end
    end
  end

  devise_for :users

  root 'xfiles#index'

  resources :xfiles, only: [:index, :show, :edit, :update] do
    resources :notes do
      collection do
        get :search
      end

      member do
        post :watch
      end
    end
  end

  resources :notes, only: [] do
    resources :comments, only: [:create]
    resources :tags, only: [] do
      member do
        delete :remove
      end
    end
  end

  resources :assets, only: [:show, :new], path: :files
end

app/models/xfile.rb
class Xfile < ActiveRecord::Base
	validates :name, presence: true
	has_many :notes, dependent: :delete_all
	has_many :roles, dependent: :delete_all

	def has_member?(user)
		roles.exists?(user_id: user)
	end

	[:manager, :editor, :viewer].each do | role |
		define_method "has_#{role}?" do | user |
			roles.exists?(user_id: user, role: role)
		end
	end
end

app/controllers/admin/xfiles_controller.rb
class Admin::XfilesController < Admin::BaseController
	before_action :set_xfile, only: [:show, :edit, :update, :destroy]

	def new
		@xfile = Xfile.new
	end

	def create 
		@xfile = Xfile.new(xfile_params)

		if @xfile.save
			flash[:notice] = "X-File has been created."
			redirect_to @xfile
		else
			flash.now[:alert] = "X-File has not been created"
			render "new"
		end
	end

	def destroy 
		#@xfile = Xfile.find(params[:id])
		@xfile.destroy

		flash[":notice"] = "X-File has been deleted."

		redirect_to xfiles_path
	end

	private

	def xfile_params
		params.require(:xfile).permit(:name, :description)
	end

	def set_xfile
		@xfile = Xfile.find(params[:id])
	end
end

app/controllers/xfiles_controller.rb
class XfilesController < ApplicationController
	before_action :set_project, only: [:show, :edit, :update, :destroy]

	def index
		#@xfiles = Xfile.all
		@xfiles = policy_scope(Xfile)
	end

	def show
		authorize @xfile, :show?
		#@xfile = Xfile.find(params[:id])
		@notes = @xfile.notes
	end

	def edit
		authorize @xfile, :update?
		#@xfile = Xfile.find(params[:id])
	end

	def update
		authorize @xfile, :update?
		#@xfile = Xfile.find(params[:id])
		if @xfile.update(project_params)
			flash[":notice"] = "X-File has been updated"
			redirect_to @xfile
		else
			flash.now[:alert] = "X-File has not been updated"
			render "edit"
		end
	end

	private

	def project_params
		params.require(:xfile).permit(:name, :description)
	end

	def set_project
		@xfile = Xfile.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			flash[:alert] = "The X-File you are looking for could not be found"
		redirect_to xfiles_path
	end
end

app/helpers/admin/xfiles_helper.rb
module Admin::XfilesHelper
end

app/helpers/xfiles_helper.rb
module XfilesHelper
end

app/views/xfiles/_form.html.erb
<%= simple_form_for(xfile) do |f| %>

	<!--
	<p>
		<%= f.label :name, "Название" %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description, "Дэскрипшн" %><br>
		<%= f.text_field :description %>
	</p>

	<%= f.submit %>
	-->

	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/xfiles/edit.html.erb
<div class="page-header">
	<h1>Edit X-File</h1>
</div>

<%= render "form", xfile: @xfile %>

app/views/xfiles/index.html.erb
<div class="page-header">
	<h1>X-Files</h1>
	<% admin_only do %>
		<ul class="actions">
			<li><%= link_to "New X-File", new_admin_xfile_path, class: "new" %></li>
		</ul>
	<% end %>
</div>


<div id="xfiles">
	<% @xfiles.each do | x | %>
		<h2><%= link_to x.name, x %></h2>
		<p><%= x.description %></p>
	<% end %>
</div>

app/views/xfiles/show.html.erb
<% title = "UFO - X-Files" %>
<div class="page-header">
	<h1><%= @xfile.name %></h1>

	<ul class="actions">
		<% if policy(@xfile).update? %>
			<li><%= link_to "Edit X-File", edit_xfile_path(@xfile), class: "edit" %></li>
		<% end %>
		<% admin_only do %>
			<li>
				<%= link_to "Delete X-File", 
					admin_xfile_path(@xfile), 
					method: :delete,
					data: {confirm: "Are you sure want to delete this X-File?"},
					class: "delete"
				%>
			</li>
		<% end %>
	</ul>
</div>
<h3><%= @xfile.description %></h3>

<div class="page-header">
	<h2>Notes</h2>

	<ul class="actions">
		<li>
			<%= form_tag search_xfile_notes_path(@xfile), method: :get, class: "form-inline" do %>
				<%= label_tag "search", "Search", class: "sr-only" %>
				<%= text_field_tag "search", params[:search], class: "form-control" %>
				<%= submit_tag "Search", class: "btn btn-default" %>
			<% end %>
		</li>
		<li>
			<% if policy(Note.new(xfile: @xfile)).create? %>
				<%= link_to "New note", new_xfile_note_path(@xfile), class: "new" %>
			<% end %>
		</li>
	</ul>
</div>

<ul id='notes'>
	<% @notes.each do | note | %>
		<li>
			#<%= note.id %>
			<%= link_to note.title, [@xfile, note] %>
			<%= render note.state if note.state %>
		</li>
	<% end %>
</ul>